Need to merge branch dev into branch master
WildCodeSchool/remotefr-js-0920-p2-hearthstone pull request #21
Opened 2020-11-05 09:14 UTC by PainJustine

Here is our header, home page with presentation of the game, and footer.

2020-11-05 10:00 UTC, bhubr requested changes
La plupart des points ne sont pas trop bloquants. Pour l'instant appliquez le conseil sur les items de la navbar... Pour le reste, si vous n'avez pas le temps maintenant, gardez les suggestions de côté !

2020-11-05 10:00 UTC, bhubr commented on debug.log
> +[1103/233012.062:ERROR:directory_reader_win.cc(43)] FindFirstFile: Le chemin d�acc�s sp�cifi� est introuvable. (0x3)
Vous pourrez faire un `git rm debug.log` et ajouter `debug.log` au `.gitignore`

2020-11-05 10:00 UTC, bhubr commented on src/App.test.jsx
> +// });
Comme on ne va pas voir les tests de composants (en tout cas pas tout de suite), autant effacer ce fichier plutôt que de tout commenter : `git rm src/App.test.jsx`

2020-11-05 10:00 UTC, bhubr commented on src/App.jsx
> +// import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';
Là c'est commenté (et aussi dans `index.jsx`), d'une façon générale je suis plutôt partisan d'importer `BrowserRouter` depuis `index.jsx` plutôt que `App.jsx` (les imports de `Switch` et `Route` restent ici).

Pas d'action requise ici pour l'instant :wink:.

2020-11-05 10:00 UTC, bhubr commented on src/components/Footer.css
> +  /* background-color: rgba(124, 81, 42, 0.7); */
Attention à ne pas laisser traîner trop de choses en commentaires (dans le CSS comme ailleurs). Par ailleurs bizarre, le commentaire ligne 11 est ouvert mais pas fermé, ça aurait pu générer une erreur !

2020-11-05 10:00 UTC, bhubr commented on src/components/Footer.css
> +  max-width: 2400px;
Houla, 2400px c'est beaucoup ! À ce stade je me demande si c'est bien utile (à voir plus tard)

2020-11-05 10:00 UTC, bhubr commented on src/components/Header.css
> +    font-family: 'Berkshire Swash', cursive;
D'une façon générale, pas besoin de redéfinir les styles qui restent les mêmes en desktop qu'en mobile, comme ici la font-family.

2020-11-05 10:00 UTC, bhubr commented on src/components/Header.jsx
> +              active ? 'nav-list-item-active' : 'nav-list-item-inactive'
Comme ce ternaire est répété, le mieux est de calculer la valeur juste après avoir "destructuré" active depuis `this.state`, donc à la ligne 16, juste avant le `return` :

```javascript
const listItemClassName = active ? 'nav-list-item-active' : 'nav-list-item-inactive';
```

Et après sur tous les `li` vous pouvez mettre `className={listItemClassName}`.

2020-11-05 10:00 UTC, bhubr commented on src/components/PagePrinc.jsx
> +              <strong>Rarety:</strong>{' '}
en anglais c'est rarity :slightly_smiling_face:

2020-11-05 10:00 UTC, bhubr commented on src/components/Presentation.css
> +/* @import url('https://fonts.googleapis.com/css2?family=Berkshire+Swash&display=swap');
Attention code mort, si vous ne l'utilisez plus vous pouvez supprimer le fichier.

2020-11-05 10:00 UTC, bhubr commented on src/components/Presentation.jsx
> +// import React from 'react';
En fait pour rebondir sur mon comm. précédent, je pense que vous avez tout commenté en attente de l'utiliser plus tard... Mais est-ce que ça ne suffisait pas de juste mettre en commentaire l'import de `Presentation.jsx` depuis le fichier qui l'utilisait ?

2020-11-06 00:48 UTC, Cissou13 approved these changes
Work is done and fixed !

2020-11-06 07:16 UTC, bhubr approved these changes

2020-11-06 07:16 UTC, bhubr commented on src/components/Header.jsx
> +            <Link to="/research" className={navLinkActive}>
Il faudra qu'on voie si c'est vraiment nécessaire d'avoir des className changeants sur le `ul`, les `li`, les `a`. Il y a aussi le `NavLink` de React Router qui peut gérer les styles sur un lien actif... C'est juste une remarque à garder de côté 😉

2020-11-06 07:17 UTC, bhubr commented
Dites-moi si vous avez bien les droits pour merger vous-mêmes, sinon je le fais !

2020-11-06 08:17 UTC, PainJustine commented
Je n'ai pas les droits pour merger !

2020-11-06 09:14 UTC, merged